default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= Settings.db.host || 'localhost' %>
  port:     <%= Settings.db.port ||5432 %>
  database: <%= Settings.db.name %>
  pool:     <%= Settings.db.pool || 15 %>
  username: <%= Settings.db.user %>
  password: <%= Settings.db.pass %>

development:
  <<: *default

test:
  <<: *default

staging:
  primary:
    <<: *default
    database: <%= Settings.db.name %>

  queue:
    <<: *default
    database: <%= Settings.db.name %>

  cache:
    <<: *default
    database: <%= Settings.db.name %>

  cable:
    <<: *default
    database: <%= Settings.db.name %>


production:
  primary:
    <<: *default
    database: <%= Settings.db.name %>

  queue:
    <<: *default
    database: <%= Settings.db.name %>

  cache:
    <<: *default
    database: <%= Settings.db.name %>

  cable:
    <<: *default
    database: <%= Settings.db.name %>
